#ifndef ENGINE_CONSTANTS_H_INCLUDED
#define ENGINE_CONSTANTS_H_INCLUDED

#define TONE_COUNT (3)
#define WAVE_COUNT (2)
#define NOISE_COUNT (1)
#define CHANNEL_COUNT (TONE_COUNT+NOISE_COUNT+WAVE_COUNT)

#endif // ENGINE_CONSTANTS_H_INCLUDED
