#ifndef ENGINE_CONSTANTS_H_INCLUDED
#define ENGINE_CONSTANTS_H_INCLUDED

#define TONE_COUNT (13)
#define WAVE_COUNT (2)
#define NOISE_COUNT (1)
#define CHANNEL_COUNT (TONE_COUNT+NOISE_COUNT+WAVE_COUNT)

#define MICROSECONDS_PER_MILLISECOND (1000)

#define AUDIO_SAMPLE_RATE_IN_HZ (22050)
#define AUDIO_LATENCY_REQUESTED_IN_MILLISECONDS (90)
#define AUDIO_LATENCY_REQUESTED_IN_SAMPLES ((AUDIO_LATENCY_REQUESTED_IN_MILLISECONDS * AUDIO_SAMPLE_RATE_IN_HZ) / 1000)
#define AUDIO_LATENCY_MAX_IN_MILLISECONDS (1000)
#define AUDIO_LATENCY_MAX_IN_SAMPLES ((AUDIO_LATENCY_MAX_IN_MILLISECONDS * AUDIO_SAMPLE_RATE_IN_HZ) / 1000)
#define AUDIO_WAVEFORM_DURATION_MAX_IN_MILLISECONDS (4000)
#define AUDIO_WAVEFORM_DURATION_MAX_IN_SAMPLES ((AUDIO_WAVEFORM_DURATION_MAX_IN_MILLISECONDS * AUDIO_SAMPLE_RATE_IN_HZ) / 1000)
#define AUDIO_BUFFER_DURATION_MAX_IN_MILLISEC (AUDIO_WAVEFORM_DURATION_MAX_IN_MILLISECONDS + AUDIO_LATENCY_MAX_IN_MILLISECONDS)
#define AUDIO_BUFFER_SIZE ((AUDIO_BUFFER_DURATION_MAX_IN_MILLISEC * AUDIO_SAMPLE_RATE_IN_HZ) / 1000)

#endif // ENGINE_CONSTANTS_H_INCLUDED
