#+TITLE: Project Burro Game Engine Implementation TODO


I'm giving up on the C+GLib+Gtk version of the engine because it will never get finished.
I'm moving to a more traditional C++, SDL2 engine, but I still doing soft rendering in Cairo.
  
* INI file parser
  GNU Ragel can be used to write the parser.
** Model: hash table
** Parser: INI file parser
** Construct: User-space disk IO -> INI file parser to do local modifications
** Construct: Art-pack disk IO -> INI file parser to do defaults
** Debug Construct: stream IO -> INI file parser
  
* Console Menu
  The console menu is a drop-down on-screen menu used by the debug menu and debug viewer.
** Model: console text info
** Model: bitmap font
** Parser: Bitmap font parser (BDF?)
** Debug Parser: Console text model info (ECMA-48?)
** View: console-to-texture renderer
** Construct: Art-pack bitmap font -> Bitmap font parser for default font
** Debug Construct: stream IO -> Bitmap font parser
** Debug Construct: stream IO -> Console text parser

* Debug Menu and Viewer
  The debug menu uses the console to display a list of variables and commands.  Each menu
  entry does one of the following
  - boolean display and toggling
  - integer display and modification
  - fixed-point display and modification
  - run thunk command
  - jump to other menu
** Model: menu entry
** Model: menu
** Model: all menus
** View: when not hidden, model-to-console render
** Controller: receive keyboard commands to control menu

* Artpack
  An archive file where resources are extracted by a path-like string or a SID. ISO9660 or USTAR will be
  used for this.
  
* String table
  A SID->string hash table. GNU GPerf could be used for this.
  
* Low-level
** Renderer
   Console, if active, will be painted to the top-layer.
** Controller
   Menu subsystem, if active, will intercept keyboard commands
** Sound
   Console, if active, may send a beep to the beep audio channel.

----------------------------------------------

OLD STUFF

----------------------------------------------


* The Engine
** X layer - low-level paranoid C wrapper
    In the X layer are wrappers around the Glib, Gtk, Cairo, Pulseaudio, and Guile functions
    that agressivly assert input parameters and throw critical warnings when they fail.  This
    way they can either be treated as errors (during development) or be ignored during release.
    
** Y layer - game engine subsystems
    In this layer, the components that make up a 2D sprite-and-tile game engine are defined.
    Important components are the main loop, the audio engine, the sprite-and-tile display
    engine, and keyboard input.  There are also minor components like the INI file reader and
    the random number generator.  Graphics are stored in a specific dialect of TGA files,
    and the library to read them is here.  Songs are store in a text format and samples are stored
    in a binary format, and the library to read those formats are in here as well.
    
    Each subsystem will define its public API in a C header.
    
** Z layer - game engine main and scripting language
    In this layer is the top-level of the game engine and the interface to the scripting language.

    The basic idea is that there is a main loop, and about every 1/60 of a second, the engine
    releases control to the scripting language and calls a function called "update".  It
    presents to the scripting language an API that it may use during its "update" call.
    
    The API is described in C headers in the Y layer and then wrapped using SWIG into a
    scripting language API.

* The Game
** The α layer - low-level paranoid wrapper
    Don't know if this is necessary, but, this would be regular library functions that are
    agressivly type-checked.

** The β layer - game subsystems
    In this layer are the game subsystems.  Menuing systems, objects that represent monsters
    or projectiles, and other such pseudoclasses.
    For example,
    - Item Generator
    - Item System
    - Inventory System
    - Character System
    - Combat
    - NPC Dialog
    - NPC Actions
    - Vendor System
    - Crafting system
    - Achievements system
    - ToolTip system
    - Harvesting System
    - Quest System
    - Movable map objects
    
** The ɣ layers - game logic
    In this layer is the code that describes the game logic.

* The Data
    The data consists of TGA sprites and tiles, MIDI-like song files, and WAV audio files.

------------------    

* Debugging file - $(userdata)/$(project)/debug.ini
  The debugging file is a glib key-value file in the user config
  directory.
* User options storage $(userdata)/$(project)/options.ini
  A Glib key-value file in the user config directory



* Directories
If we followed all the specifications, data would be spread all over
the the filesystem.
** Savefiles - XDG_DATA_HOME
   when run in tree: $(topdir)/share
   when installed: g_get_user_data_dir()
** User configuration - XDG_CONFIG_HOME
   when run in tree: $(topdir)/config
   when installed: g_get_user_config_dir()
** Debug options - XDG_CONFIG_HOME
   when run in tree: $(topdir)/config
   when installed: g_get_user_config_dir()
** Graphical assets
   when run in tree: 
     $(topdir)/data/graphics
     $(topdir)/data/sound
   when installed: $(datadir)/PACKAGE/
** Scripts
   when run in tree:
     GUILE_LOAD_PATH is $(srcdir)/g
     GUILE_LOAD_COMPILED_PATH is also $(srcdir)/g
   when installed: $(datadir)/PACKAGE/scripts
     GUILE_LOAD_PATH is $(srcdir)/scripts
     GUILE_LOAD_COMPILED_PATH is also $(srcdir)/scripts
